#!/bin/bash
set -euo pipefail

REPO_ROOT="${1:-$(pwd)}"
ARTIFACT_ROOT="${2:-artifacts}"
VERSION_TEXT="$(tr -d '[:space:]' < "$REPO_ROOT/VERSION")"
TAG_NAME="${KANO_RELEASE_TAG:-v${VERSION_TEXT}}"
REPO_SLUG="${KANO_GITHUB_REPOSITORY:-kanohorizonia/kano-git-master-skill}"
ASSET_BASE_URL="${KANO_RELEASE_ASSET_BASE_URL:-https://github.com/${REPO_SLUG}/releases/download/${TAG_NAME}}"
OUTPUT_DIR="${KANO_PACKAGE_MANAGER_RECIPE_ROOT:-Release/package-managers}/apt"
PACKAGE_NAME="${KANO_APT_PACKAGE_NAME:-kano-git}"

calc_sha256() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | awk '{print $1}'
    return 0
  fi
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$path" | awk '{print $1}'
    return 0
  fi
  if command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 "$path" | awk '{print $NF}'
    return 0
  fi
  echo "ERROR: sha256sum, shasum, or openssl is required to hash $path" >&2
  exit 115
}

find_linux_archive() {
  local root found
  for root in "$ARTIFACT_ROOT" "$ARTIFACT_ROOT/packages" artifacts artifacts/packages; do
    [ -d "$root" ] || continue
    found="$(find "$root" -maxdepth 1 -type f \( -iname '*linux-x64*.tar.gz' -o -iname '*linux-x64*.tgz' -o -iname '*linux-x64*.tar' -o -iname '*linux*.tar.gz' -o -iname '*linux*.tgz' -o -iname '*linux*.tar' \) | sort | head -n 1 || true)"
    if [ -n "$found" ]; then
      printf '%s\n' "$found"
      return 0
    fi
  done
}

cd "$REPO_ROOT"
LINUX_ARCHIVE="$(find_linux_archive)"
if [ -z "$LINUX_ARCHIVE" ]; then
  echo "ERROR: Linux release archive not found under $ARTIFACT_ROOT or artifacts/packages" >&2
  exit 114
fi

ARCHIVE_FILE="$(basename "$LINUX_ARCHIVE")"
ARCHIVE_SHA256="$(calc_sha256 "$LINUX_ARCHIVE")"
mkdir -p "$OUTPUT_DIR"

cat > "$OUTPUT_DIR/README.md" <<EOF
# ${PACKAGE_NAME} apt repository dry-run payload

This directory is generated by Jenkins as the apt package-manager lane input.
It is intentionally dry-run metadata until the internal apt repository URL,
signing key, Debian control metadata, and publish credentials are configured.

Source release asset:

- ${ASSET_BASE_URL%/}/${ARCHIVE_FILE}
- sha256: ${ARCHIVE_SHA256}

The current Linux v1 install artifact is the normalized tarball. Debian package
authoring should wrap this payload into a .deb before non-dry-run apt publish.
EOF

cat > "$OUTPUT_DIR/${PACKAGE_NAME}.apt-recipe.json" <<EOF
{
  "schemaVersion": 1,
  "kind": "kano-apt-recipe",
  "packageName": "${PACKAGE_NAME}",
  "version": "${VERSION_TEXT}",
  "tag": "${TAG_NAME}",
  "sourceArchive": {
    "fileName": "${ARCHIVE_FILE}",
    "url": "${ASSET_BASE_URL%/}/${ARCHIVE_FILE}",
    "sha256": "${ARCHIVE_SHA256}"
  },
  "publish": {
    "dryRun": true,
    "repositoryUrlEnv": "KANO_APT_REPO_URL",
    "targetBranchEnv": "KANO_APT_TARGET_BRANCH",
    "credentialEnv": "KANO_APT_REPO_TOKEN"
  },
  "debian": {
    "package": "${PACKAGE_NAME}",
    "section": "utils",
    "priority": "optional",
    "architecture": "amd64",
    "summary": "Kano Git command line tooling",
    "requiresDebAuthoring": true
  }
}
EOF

cat > "$OUTPUT_DIR/debian-control.stub" <<EOF
Package: ${PACKAGE_NAME}
Version: ${VERSION_TEXT}
Section: utils
Priority: optional
Architecture: amd64
Maintainer: Kano Horizonia <jenkins@kanohorizonia.local>
Description: Kano Git command line tooling
 This is a dry-run control stub. Fill Depends, install layout, maintainer
 scripts, signing, and repository metadata before enabling non-dry-run apt publish.
EOF

echo "$OUTPUT_DIR"
